# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Becker research group
email: stephen.becker@colorado.edu
description: Becker research group at the University of Colorado Boulder
#description: >- # this means to ignore newlines until "baseurl:"
# Write an awesome description for your new site here. You can edit this
# line in _config.yml. It will appear in your document head meta (for
# Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://stephenbeckr.github.io" # the base hostname & protocol for your site, e.g. http://example.com
#twitter_username: jekyllrb

# For deploying to CU's servers (NOT for github)
# baseurl: "faculty/becker/test"
# url: "https://amath.colorado.edu"

github_username:  stephen.beckr

# Minima will auto-generate the links in the header, but I can hard-code them
#  here if I want to control the order they appear
#  See https://github.com/jekyll/minima#customize-navigation-links
header_pages:
  - index.md
  - people.md
  - papers.md
  - research.md
  - teaching.md
  - software.md
  - K12.md

plugins:
  - jekyll-feed
  - jekyll-remote-theme # SRB adding, following https://github.com/pages-themes/leap-day
# This issue also recommends using -jekyll-remote-theme
# https://github.com/jekyll/minima/issues/472
# For public GitHub, remote themes must be in the form of OWNER/REPOSITORY
# You may also optionally specify a branch, tag, or commit to use by appending an @ and 
#  the Git ref (e.g., benbalter/retlab@v1.0.0 or benbalter/retlab@develop)

# Build settings
#theme: minima
# For minima, can also use the 2.5-stable branch: https://github.com/jekyll/minima/tree/2.5-stable
remote_theme: jekyll/minima@master


#remote_theme: pages-themes/leap-day@v0.2.0



# SRB: shows excerpts from posts, https://github.com/jekyll/minima
show_excerpts: true

#https://jekyllrb.com/docs/assets/#sassscss
sass:
    sass_dir: _sass

# Github version of minima cannot find 'auto' skin
# Even comment this out doesn't fix since it cannot find 'classic'
#
# Manually copy cp $(bundle show minima)/_sass/minima/skins/* to local directory:w
#    Oct 2023, changing skin from 'auto' to 'classic' since
#    in auto (which means use dark mode if user has OS in dark mode)
#    then my fonts don't work so well.   Or, maybe I can fix???
#    See aliases used in _sass/minima/skins/auto.scss
#    Hmm, I think those variables only work in .scss files (SAS files that generate CSS files)
#     so probably won't help without a major change.

minima:
  skin: auto

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
